---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-backstage-system
  description: Description of sample-backstage-system
spec:
  owner: group:team1
  domain: sample-backstage-domain