apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-backstage-app-1
  description: Some description of the sample-backstage-app-1 component
spec:
  type: service
  lifecycle: production
  owner: group:group-name
  system: system-name
  dependsOn:
    - resource:default/sample-backstage-app-1-db
  providesApis:
    - sample-backstage-app-1-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-backstage-app-1-api
  description: Some description of the sample-backstage-app-1-api interface
spec:
  type: openapi
  lifecycle: production
  owner: group:guest
  system: sample-backstage-system
  definition: |
    $json: https://petstore3.swagger.io/api/v3/openapi.json
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sample-backstage-app-1-db
  description: Description of sample-backstage-app-1-db
spec:
  type: database
  owner: group:guest
  system: sample-backstage-system
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sample-backstage-location
spec:
  targets:
    - ./catalog-info-team.yaml
    - ./catalog-info-members.yaml
    - ./catalog-info-domain.yaml
    - ./catalog-info-system.yaml